UI/Main GUI.ui
UI_test.py

- *.jpg, *. jpeg, *.png 파일 지원
-  파일 탐색기를 통해 이미지 불러오기
- QFileDialog 클래스 활용
- 크기에 맞게 Reshape
- QPixmap 클래스 활용

Feat: Image FIle Open & Display Canvas

---

UI/Add Lable Dialog.ui
UI/Main GUI.ui
UI_test.py

- 새 창으로 Dialog 
- LineEdit 및 PushButton으로 구현
- GroupID 기능 보류
- Main Window와 동기화 완료

Feat: Add New Label

---

UI_test.py

* 이미지 파일을 열기 위한 openImage() 함수 추가
* QFileDialog 클래스 이용
* File full path name 반환
* 반환 받은 Filename을 이용하여 loadImage 함수 호출
* 이미지 파일을 Load/Display 하기 위한 loadImage() 함수 추가
* OpenCV 함수 cv2.imread()를 이용하여 파라미터 값 filename을 입력 후 이미지 읽기
* OpenCV의 경우 BGR 형태이므로 PyQt GUI에 출력하기 위해 RGB형태로 변환
* shape을 이용하여 height, width, channel 반환
* QImage() 클래스 생성
* QPixmap.fromImage 함수를 이용하여 Image를 Pixmap으로 변환
* Label canvas 영역에 변환된 Pixmap 설정(출력)

Feat: Add open/load image

---

UI/Image From Camera.ui
UI/Main GUI.ui
UI_test.py

- QThread() 클래스 사용
- 현재 창 켰을 때 실시간 모니터링만 가능
- 캡쳐기능 미구현
- 주석처리됨

Feature: IP Camera 캡쳐 기능 일부 구현

---

UI_test.py

* openImage() 함수 내 예외 처리 부분의 필요성이 없어 제거

Fix: Delete exception in FileOpen()

---

UI_test.py

* Global 변수 `GLOBAL_menubar_Flag`추가, 초기값 False
* refresh() 함수 호출
* True 경우 menuBar :  Edit, Zoom / menuItem:  Save  활성화
* False 경우 menuBar :  Edit, Zoom  / menuItem:  Save  비활성화

feat : add menuRefresh

---

Mediapipe_test.py
UI_test.py

- 캠 이미지 캡쳐 기능 추가
- 720p 해상도
- 캡쳐 이후 메인 윈도우에 출력
- 제스쳐 인식 기능 추가
- 메인 윈도우에는 표시 안됨

Feature: IP Cam을 통한 이미지 캡쳐

---

UI_test.py

- 캡쳐 시 딜레이 발생하는 문제 해결
- 캡쳐 함수를 최우선 순위로 변경

fix: reduce capture delay

---

UI/Main GUI.ui
UI_test.py

- 이미지 스크롤 사용기능 추가
- 확대/축소 기능과 연계 필요
- QScroll() 클래스 사용

Feat: Image Scroll Function

---

UI_test.py

- 이미지를 json 형태의 파일로 저장
- shapes
- label name
- points
- shape type
- imagePath
- imageHeight
- imageWidth

feat : json 저장 함수 추가

---

simple_MVVM.py

Feat: simple mvvm model

---

Model.py
ViewModel/Canvas.py

- widget 클릭시 포커스 맞춤 설정
- 키보드, 마우스 이벤트 함수 추가

feat : add key, mouse wheel event 

---

Model.py
ViewModel/Canvas.py

- 포커스가 잡히지 않은 상태에서 마우스 키보드 이벤트를 줄 경우 강제종료 에러 발생
- 포커스 이벤트 함수 추가
- canvas 영역 포커싱 True/False 지정

feat : 이벤트 에러 보완 

---

Model.py
ViewModel/Canvas.py

* imgData 변수 제거 후 변경
* getImgData() 수정
* menuRefresh() 파라미터 제거
* initUI(), initData() 함수 추가

fix : 변수 이름 변경 및 초기화 함수 추가

---

Utils/ConvertAnnotation.py
ViewModel/Canvas.py

* os 모듈 가져오기
* openImage 함수 내 setAnnotInfo 설정
* saveJson 함수 추가
* dict2Json 함수 추가

feat : saveJson 함수 작업

---

Model.py
ViewModel/Canvas.py

- Model의 Annot Info를 참조해 도형별 라벨 정보 출력( Points )
- 정규화된 좌표이기 때문에 좌표점에 폭, 높이를 곱해줌
- 현재 Polygon에 문제 발생

Feature: display annot info

---

Model.py
Utils/ConvertAnnotation.py
ViewModel/Canvas.py

openImage 변경
- self.jsonPath 초기화
- 불러올 파일의 확장자가 json이거나 이미지 파일의 json 파일이 존재 할 경우
- json 파일 읽어서 이미지 출력
- 이미지 파일만 존재할 경우
- autoAnnotation을 호출하여 작업된 내용들을 setAnnotInfo 설정(미구현)

feat : openImage

---

ViewModel/Canvas.py

- openImage에서 저장된 json의 정보를 불러와서 출력할 경우 저장된 annot을 불러와 표시가 되어야 함.
- displayImage 호출 전에 추가

feat: openImage 함수 내 setDisplayAnnot 추가

---

ViewModel/Canvas.py

- ctrl + O → openFile() 함수 실행
- ctrl + S → saveJson() 함수 실행

feat : KeyPressEvent() 함수 내 단축키 작업

---

Model.py

fix : dict.copy() 설정

---

ViewModel/AddLabelDialog.py
ViewModel/Canvas.py

- json의 'label name' 데이터를 불러와 label_list 출력
- Error correction

fix : label_list 전반 수정

---

ViewModel/Canvas.py

- 오른쪽 마우스 클릭시 이벤트 발생
- draw 기능 추가

feat : Context menu 추가

---

ViewModel/AddLabelDialog.py
ViewModel/Canvas.py

fix : setLabel 수정

---

ViewModel/Canvas.py

fix : 코드 정리

---

Model.py
ViewModel/Canvas.py

Error
- 작업한 이미지 저장 후 다른 파일을 불러온 후에 label 추가시 label list에 기존에 작업했던 label이 존재
해결
- model에서 initLabelList() 함수 추가
- canvas openImage() 함수에서 initLabelList() 호출

fix : label list 수정

---

ViewModel/Canvas.py

- json 을 불러와서 label을 추가할 때 Label dialog창에 label list들이 존재 안함
- -openFile() 함수에서 파일 불러올 때 setLabel()을 호출

fix : openFile() 수정

---

Model.py
ViewModel/Canvas.py

- 현재 구현했지만 오류가 많아 사용 불가 판정으로 삭제함
- 한 점만 옮기지 못하는 문제 발생
- Display 시 이전 그림과 겹쳐서 표시되는 문제 발생
- 필요 없는 로직 전부 삭제
- 가독성을 위해 일부 코드 위치 변경
- 모든 알고리즘 구조는 동일

Refactor: 코드 가독성 증가

---

Model.py
Utils/ConvertAnnotation.py
Utils/ImageProc.py
ViewModel/Canvas.py

- 코드 간결 목적
- img2QPixmap 함수 추가

Refactore: Code refactoring 

---

Utils/ConvertAnnotation.py
ViewModel/AddLabelDialog.py
ViewModel/Canvas.py

* setLabel() 함수 수정
* loadLabelList() 함수 추가
* saveJson() 수정
* loadLabelList() 함수 수정

fix: Error Correction

---

Model.py
Resource/UI/Main GUI.ui
ViewModel/Canvas.py

- 구현 완료
- 이동하려는 점 기준 10px 크기의 Dot 생성
- 클릭중에만 이동 가능
- mousePressEvent 활용
- draw중에는 실행 안됨
- 현재 잔상생기는 문제 발생

Feature: retouch

---

Model.py
Resource/UI/Main GUI.ui
Utils/AutoAnnotation.py
View.py
ViewModel/Canvas.py

- 일부 함수 이름 변경
- Utils에 있는 함수 일부 변경 후 적용
- 좌표 못찾을 시 Mediapipe 모듈에서 y값 음수로 초기화
- 음수일 시 0,5, 0.5로 좌표 초기화

Feature: auto annotation

---

ViewModel/Canvas.py

fix: drawGesturePoly 수정

---

ViewModel/Canvas.py

- 기존 제스처 함수 제거
- right/left 제스처 함수 추가

fix: contextMenuEvent 수정

---

Model.py
View.py
ViewModel/AddLabelDialog.py
ViewModel/AddObjectDialog.py
ViewModel/Canvas.py

- 삭제 기능 추가
- ObjectList에서 클릭하면 해당 Object 파란색으로 표시
- 더블클릭 시 삭제

Feature: delete

---

Model.py
ViewModel/AddObjectDialog.py
ViewModel/Canvas.py

feat: undo 기능 추가

---

Model.py
ViewModel/AddObjectDialog.py
ViewModel/Canvas.py

- Undo 기능 추가 이후 Object List에서 버그 발생
- List Index에서 벗어나는 문제
- 애초에 모든 Index를 현재 annot_info 기준으로 변경함으로써 해결
- Undo하면 메인 윈도우의 Object리스트도 변경

Fix: conflict

---

ViewModel/Canvas.py

fix: openDialog 수정

---

View.py
ViewModel/Canvas.py

- Gesture Polygon 가독성 향상
- Circle 중심점 Display
- Object list 비정상작동 오류 해결
- Dot 기능 오류 해결

Fix: 기타 버그

---

HandAnnot.py
Utils/ConvertAnnotation.py
Widgets/Display.py
Widgets/Draw.py

Refactor: 일부 함수 구현

---

HandAnnot.py
Utils/ConvertAnnotation.py
Widgets/AddObjectDialog.py
Widgets/Display.py
Widgets/Draw.py

- 구현 완료
- 정규화, 역정규화 함수 정의
- 기타 출력 및 플래그 설정 정의

Refactor: Display Annotation Info

---

HandAnnot.py
Model.py
Utils/ImageProc.py
Widgets/Display.py
v1/Model.py

- Zoom 테스트 코드 작성 완료
- Display 시 Scaled Image 적용되는지 확인
- 구현 완료

Refactor: zoom Test

---

HandAnnot.py
Widgets/Display.py
Widgets/Draw.py
Widgets/Zoom.py

- zoom 기능 이식 완료
- scrollArea.setWidget()말고 Stacked Widget으로 변경
- 가운데 정렬 안되는 문제 있음
- 이미지 불러오기 시 height 살짝 늘어나는 문제 있음

Refactor: Zoom

---

HandAnnot.py
Widgets/Draw.py
Widgets/Zoom.py

- 기능 추가
- 문제 없음
- 기능추가
- 문제 없음

Refactor: Auto Annotation, Retouch

---

HandAnnot.py
Resource/UI/Main GUI.ui
Widgets/Delete.py
Widgets/Display.py
Widgets/Draw.py
Widgets/Zoom.py

Refactor: 변경사항 적용

---

HandAnnot.py
Model.py
Utils/ImageProc.py
Widgets/Zoom.py

- openFile
- setZoom()
- saveJson

Refactor: 함수 코드 재구조화

---

HandAnnot.py
Widgets/Draw.py

fix: Draw.py contextMenuEvent 제거

---

HandAnnot.py

undo
* 되돌리기 기능
loadLabelList, loadObjectList 분할
* 서로 분할하여 독립적으로 실행

feat: undo, loadLabelList, loadObjectList 함수 추가

---

HandAnnot.py

fix: setDraw, setGesture 코드 간결

---

HandAnnot.py

fix: menuRefresh 변경

---

Model.py

fix: model.py 변수 제거

---

Widgets/Zoom.py

fix: img2QPixmap 함수 제거

---

Model.py

fix: model 함수 위치 변경

---

HandAnnot.py
README.md
Resource/UI/Add Object Dialog.ui
Widgets/AddObjectDialog.py

- Release를 하기 위한 코드 추가
- exe 파일 안에 UI 파일 첨부를 위한 코드 작업추가
- 리드미 수정 및 링크 추가

Feature: Release
